/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MnemeAttestation } from "./MnemeAttestation";
export * as factories from "./factories";
export { MnemeAttestation__factory } from "./factories/MnemeAttestation__factory";
