/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MnemeAttestationInterface extends Interface {
  getFunction(
    nameOrSignature: "attest" | "getAttestation" | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MemoryAttested"): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace MemoryAttestedEvent {
  export type InputTuple = [
    memoryId: string,
    contentHash: BytesLike,
    attester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    memoryId: string,
    contentHash: string,
    attester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    memoryId: string;
    contentHash: string;
    attester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MnemeAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): MnemeAttestation;
  waitForDeployment(): Promise<this>;

  interface: MnemeAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [memoryId: string, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [memoryId: string],
    [
      [string, string, bigint] & {
        contentHash: string;
        attester: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  verify: TypedContractMethod<
    [memoryId: string, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [memoryId: string, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [memoryId: string],
    [
      [string, string, bigint] & {
        contentHash: string;
        attester: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [memoryId: string, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "MemoryAttested"
  ): TypedContractEvent<
    MemoryAttestedEvent.InputTuple,
    MemoryAttestedEvent.OutputTuple,
    MemoryAttestedEvent.OutputObject
  >;

  filters: {
    "MemoryAttested(string,bytes32,address,uint256)": TypedContractEvent<
      MemoryAttestedEvent.InputTuple,
      MemoryAttestedEvent.OutputTuple,
      MemoryAttestedEvent.OutputObject
    >;
    MemoryAttested: TypedContractEvent<
      MemoryAttestedEvent.InputTuple,
      MemoryAttestedEvent.OutputTuple,
      MemoryAttestedEvent.OutputObject
    >;
  };
}
